version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      codeigniter_net:
    ports:
      - "8191:90"
    restart: always

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/public
    networks:
      codeigniter_net:

networks:
  codeigniter_net:
